import type { Metadata } from "next";
import { Inter } from "next/font/google"; // Changed font import
import "./globals.css";
import Link from 'next/link'; // Import Link

const inter = Inter({ subsets: ["latin"] }); // Changed font variable

export const metadata: Metadata = {
  title: "Online Shopping App", // Updated title
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}> {/* Updated className */}
        <nav>
          <ul style={{ listStyle: 'none', padding: 0, display: 'flex', gap: '10px', marginBottom: '20px', borderBottom: '1px solid #ccc', paddingBottom: '10px' }}>
            <li><Link href="/">Home</Link></li>
            <li><Link href="/products">Products</Link></li>
            <li><Link href="/cart">Cart</Link></li>
            <li><Link href="/checkout">Checkout</Link></li>
            <li><Link href="/login">Login</Link></li>
            <li><Link href="/register">Register</Link></li>
            <li><Link href="/admin/dashboard">Admin Dashboard</Link></li>
          </ul>
        </nav>
        {children}
      </body>
    </html>
  );
}
